### ISSUE TITLE
Timed out while waiting

### ISSUE THREAD

**Issue by bergpb** [sethmlarson/trytravis#28]
Hello, i'm download latest version from pip and i got this error:

Waiting for a Travis build to appear for `5f64750a1f993b8182eb9b50c78e7cef7b853d40` after `2020-01-05 13:25:29`...
ERROR: Timed out while waiting for a Travis build to start. Is Travis configured for `https://github.com/bergpb/test-trytravis`?

I'm find some solutions in closed issues but not work for me.
Time machine at run the command: 13:05 07/01/2020

**Comment by sethmlarson** [comment]
I'm unsure what caused this, I no longer have time to maintain this tool.

**Comment by bergpb** [comment]
Okay, its a great project, help me so much to test my travis configurations before commit.
I try to fix and submit a pull request after.

**Comment by TomBugnon** [comment]
For future reference, I had this issue as well because the build failed in travis CI due to a syntax error in the .travis.yml
